const API_URL = 'https://script.google.com/macros/s/AKfycbzK9XfQkYYsTps0BATkKYS1zzZe5vdRbLw7mmMFWLbUuOBQAM_ZT7d4XbTJ7k84TlUe/exec';

const GUIDES = ['Alexandra', 'Lea', 'Damaris', 'Stefan', 'Carmen'];
const CATEGORIES = ['Bau', 'Betrieb', 'Prozesse', 'IT / Technik', 'Sicherheit', 'Ausstattung / Material', 'Kommunikation', 'Sonstiges'];
const PRIORITIES = ['Niedrig', 'Mittel', 'Hoch'];
const STATUS = ['offen', 'in Abklärung', 'beantwortet'];

const DEMO = [
  { order: 'Start', floor: '', station: 'Start', topic: 'Badge beim Hauptempfang Securitas abholen\nBlaue Überzieher-Schuhe richten\nPräsenzkontrolle durchführen', special: '', way: '', nextStation: 'Eingang Mitarbeitende' },
  { order: 1, floor: '0', station: 'Eingang Mitarbeitende', topic: 'Zutrittsmanagement\nBadgesteuerung\nLiftsteuerung', special: 'Bettenlift nur für Patiententransporte', way: 'Ambi Treppe C m. Badge → zu Fuss ins UG2 zur Wäscheausgabe', nextStation: 'Wäscheausgabe' },
  { order: 2, floor: 'UG2', station: 'Wäscheausgabe', topic: 'Regelung Berufswäsche', special: '', way: 'zu Fuss zu Garderobe', nextStation: 'Garderobe' },
  { order: 3, floor: 'UG2', station: 'Garderobe', topic: 'Nutzung Garderobenschränke\nZuteilung persönliche Schliessfächer', special: 'persönliche Schliessfächer nur für MA mit Berufswäsche\nSammlung der dreckigen Berufswäsche vor Lift', way: 'Treppe B → zu Fuss ins UG1 zum Foyer', nextStation: 'Foyer und Aula' },
  { order: 4, floor: 'UG1', station: 'Foyer und Aula', topic: 'Rapportraum Ärzte plus grosse Sitzungszimmer', special: 'Buchen von Ressourcen\nDurchführung von Weiterbildungen', way: 'zu Fuss zu Skillsräumen', nextStation: 'Skillsräume' },
  { order: 8, floor: '0', station: 'Empfang', topic: 'Aufenthaltsraum und Snackautomaten\nAED und Notfallsituationen\nPatientenempfang', special: 'AED und REA sind mit Schildern im ganzen Haus gekennzeichnet', way: 'zu Fuss zum Eingang Notfall', nextStation: 'Notfall' },
  { order: 32, floor: '0', station: 'Haupteingang', topic: 'Abschluss Führung', special: '', way: '', nextStation: 'Tour abschliessen' }
];

const MAPS = {
  EG: {
    title: 'Karte EG',
    subtitle: 'Testkarte zur Wegführung Bettenstation im Ambi',
    html: `
      <svg class="mapSvg" viewBox="0 0 980 1320" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="EG Karte Testansicht">
        <rect width="980" height="1320" fill="#fff"/>
        <g fill="#ef9b86" opacity=".72" stroke="#2A2641" stroke-width="2">
          <rect x="55" y="70" width="850" height="190"/><rect x="55" y="320" width="370" height="250"/><rect x="540" y="320" width="365" height="250"/>
          <rect x="55" y="650" width="850" height="210"/><rect x="55" y="940" width="850" height="260"/>
        </g>
        <g fill="#f2c99a" opacity=".85" stroke="#2A2641" stroke-width="2"><rect x="55" y="265" width="370" height="105"/><rect x="55" y="570" width="210" height="160"/></g>
        <g fill="#9db8ff" opacity=".75" stroke="#2A2641" stroke-width="2"><rect x="430" y="105" width="75" height="110"/><rect x="505" y="590" width="90" height="135"/><rect x="90" y="800" width="115" height="70"/></g>
        <g stroke="#fff" stroke-width="42" stroke-linecap="round"><path d="M55 270H910"/><path d="M490 60V1200"/><path d="M55 910H910"/><path d="M55 610H910"/></g>
        <g stroke="#2A2641" stroke-width="2" opacity=".55"><path d="M55 270H910M490 60V1200M55 910H910M55 610H910"/></g>
        <path d="M180 760V680H410L455 610H555V770H705V905H280V1015" fill="none" stroke="#3CAA73" stroke-width="16" stroke-linejoin="round" stroke-linecap="round"/>
        <g fill="#3CAA73"><rect x="125" y="725" width="110" height="58" rx="10"/><rect x="358" y="690" width="118" height="58" rx="10"/><rect x="145" y="1008" width="110" height="58" rx="10"/></g>
        <g fill="#fff" font-family="Arial, sans-serif" font-size="25" font-weight="700"><text x="150" y="762">A55</text><text x="384" y="727">A49</text><text x="172" y="1045">A36</text></g>
        <g fill="#2A2641" font-family="Arial, sans-serif"><text x="55" y="44" font-size="32" font-weight="700">EG / Testkarte</text><text x="55" y="1265" font-size="24">Grüne Linie = Wegführung / Raumlabels = aus Plan übernommen</text><text x="55" y="1295" font-size="18" fill="#706b82">Für die finale Version ersetzen wir diese Testansicht durch die Originalpläne pro Geschoss.</text></g>
      </svg>`
  }
};

const state = { view: 'start', stations: DEMO, i: 0, questions: JSON.parse(localStorage.tourpilot_questions || '[]'), tour: JSON.parse(localStorage.tourpilot_tour || 'null'), filter: 'Alle', zoom: 100 };
const $ = id => document.getElementById(id);
const screen = $('screen');
const toast = $('toast');

document.querySelectorAll('[data-view]').forEach(button => { button.onclick = () => { state.view = button.dataset.view; render(); }; });
$('menu').onclick = async () => { if (!API_URL) return msg('Demo-Modus: Apps-Script-URL fehlt.'); try { await api('ping'); msg('Live-Verbindung zum Google Sheet ist aktiv.'); } catch (error) { msg('Google Sheet aktuell nicht erreichbar.'); } };
loadStations().then(render);

async function loadStations() { if (!API_URL) return; try { const response = await api('getStations'); if (response.stations && response.stations.length) state.stations = response.stations; if (state.tour?.tourId) await loadQuestions(); } catch (error) { msg('Google Sheet nicht erreichbar – Demo-Daten geladen.'); } }
async function loadQuestions() { if (!API_URL || !state.tour?.tourId) return; try { const response = await api('getQuestions', { tourId: state.tour.tourId }); if (response.questions) { const other = state.questions.filter(q => q.tourId !== state.tour.tourId); state.questions = [...other, ...response.questions]; localStorage.tourpilot_questions = JSON.stringify(state.questions); } } catch (error) {} }

function render() { document.querySelectorAll('[data-view]').forEach(button => button.classList.toggle('active', button.dataset.view === state.view || (state.view === 'questionForm' && button.dataset.view === 'questions'))); if (state.view === 'tour') return tourView(); if (state.view === 'questionForm') return questionForm(); if (state.view === 'questions') return questionsView(); if (state.view === 'finish') return finishView(); return startView(); }
function startView() { const now = new Date(); const today = state.tour?.date || now.toISOString().slice(0, 10); const time = state.tour?.startTime || now.toTimeString().slice(0, 5); const defaultTourId = 'Führung ' + today.replaceAll('-', ''); screen.innerHTML = `<section class="hero"><div><h1>Neubau TourPilot</h1><p>Mobiler Guide für Mitarbeitenden-Führungen</p></div></section><section class="grid"><h1>Tour starten</h1>${row('◷','Datum',`<input id="date" type="date" value="${esc(today)}">`)}${row('♟','Guide',`<select id="guide">${opts(GUIDES, state.tour?.guide || 'Carmen')}</select>`)}${row('⌁','Tour-ID / Führung',`<input id="tourId" value="${esc(state.tour?.tourId || defaultTourId)}">`)}${row('☷','Gruppe',`<input id="group" placeholder="z. B. Team Pflege" value="${esc(state.tour?.group || '')}">`)}${row('◴','Startzeit',`<input id="startTime" type="time" value="${esc(time)}">`)}<button id="start" class="btn primary">▶ Tour starten</button><div class="card lime"><strong>Standardroute – ${state.stations.length} Stationen</strong><p class="small">Fragen werden mit Tour-ID, Guide und Station gespeichert.</p></div><article class="card creme"><div class="split"><strong>Fun-Facts</strong><span class="pill">später</span></div><p class="small">Platzhalter für Fenster, Kabel, Fläche, Räume usw.</p></article></section>`; $('start').onclick = startTour; }
function row(iconLabel, label, field) { return `<div class="row"><span>${iconLabel}</span><div><label>${label}</label>${field}</div></div>`; }
async function startTour() { state.tour = { date: $('date').value, guide: $('guide').value, tourId: $('tourId').value.trim(), group: $('group').value.trim(), startTime: $('startTime').value, status: 'offen' }; if (!state.tour.tourId) return msg('Bitte Tour-ID eingeben.'); localStorage.tourpilot_tour = JSON.stringify(state.tour); if (API_URL) { try { await api('saveTour', state.tour); await loadQuestions(); msg('Tour im Google Sheet gestartet.'); } catch (error) { msg('Tour lokal gestartet – Sheet gerade nicht erreichbar.'); } } state.i = 0; state.view = 'tour'; render(); }
function tourView() { if (!state.tour) { state.view = 'start'; return render(); } const station = state.stations[state.i] || state.stations[0] || {}; const current = state.i + 1; const total = state.stations.length || 1; const progress = Math.round((current / total) * 100); const points = [...list(station.topic), ...list(station.special).slice(0, 3)]; const map = getMap(station.floor); screen.innerHTML = `<section class="grid" style="padding-top:14px"><div class="card"><div class="split"><strong>Station ${current} von ${total}</strong><strong>${progress}%</strong></div><div class="progress"><div class="bar" style="width:${progress}%"></div></div></div><article class="card"><div class="stationHead"><div class="stationIcon">${icon(station)}</div><div><div class="kicker">${esc(state.tour.tourId)} · ${esc(state.tour.guide)}</div><h1>${esc(station.station || 'Station')}</h1>${station.floor ? `<p>Geschoss: <span class="floor">${esc(station.floor)}</span></p>` : ''}</div></div>${points.length ? `<ul class="bullets">${points.map(item => `<li>${esc(item)}</li>`).join('')}</ul>` : '<p class="small">Keine Detailpunkte hinterlegt.</p>'}</article><article class="card lilac next"><div class="round">👣</div><div><div class="kicker">Nächste Station</div><strong>${esc(station.nextStation || 'Tour abschliessen')}</strong></div><span>›</span></article><article class="card mint next"><div class="round">⇄</div><div><div class="kicker">Weg</div><strong>${esc(station.way || station.access || 'Keine Wegführung hinterlegt')}</strong></div></article>${map ? `<button id="showMap" class="btn mapBtn">▧ ${map.title} einblenden</button>` : ''}<div class="twocol"><button id="ask" class="btn ghost">✎ Frage erfassen</button><button id="next" class="btn primary">${current >= total ? 'Abschluss' : 'Weiter'} ›</button></div><button id="prev" class="btn ghost" ${state.i === 0 ? 'disabled' : ''}>‹ Zurück</button></section>`; $('ask').onclick = () => { state.view = 'questionForm'; render(); }; $('next').onclick = () => { if (state.i < total - 1) state.i += 1; else state.view = 'finish'; render(); }; $('prev').onclick = () => { if (state.i > 0) state.i -= 1; render(); }; if (map) $('showMap').onclick = () => showMap(map); }
function showMap(map) { state.zoom = 100; const overlay = document.createElement('div'); overlay.className = 'mapOverlay'; overlay.innerHTML = `<div class="mapSheet"><div class="mapHeader"><div><h2>${esc(map.title)}</h2><p>${esc(map.subtitle)}</p></div><button id="closeMap" class="mapIconBtn">×</button></div><div class="mapTools"><button id="zoomOut" class="pill">− kleiner</button><button id="zoomReset" class="pill active">100%</button><button id="zoomIn" class="pill">+ grösser</button></div><div class="mapFrame"><div id="mapContent">${map.html}</div></div><p class="small mapNote">Mit Finger verschieben; über die Buttons zoomen.</p></div>`; document.body.appendChild(overlay); const content = overlay.querySelector('#mapContent'); const setZoom = value => { state.zoom = Math.max(70, Math.min(190, value)); content.style.width = state.zoom + '%'; overlay.querySelector('#zoomReset').textContent = state.zoom + '%'; }; setZoom(100); overlay.querySelector('#closeMap').onclick = () => overlay.remove(); overlay.onclick = event => { if (event.target === overlay) overlay.remove(); }; overlay.querySelector('#zoomOut').onclick = () => setZoom(state.zoom - 20); overlay.querySelector('#zoomIn').onclick = () => setZoom(state.zoom + 20); overlay.querySelector('#zoomReset').onclick = () => setZoom(100); }
function getMap(floor) { const raw = String(floor ?? '').trim().toUpperCase(); return (raw === '0' || raw === 'EG' || raw === 'E0') ? MAPS.EG : null; }
function questionForm() { if (!state.tour) { state.view = 'start'; return render(); } const station = state.stations[state.i] || {}; screen.innerHTML = `<section class="grid" style="padding-top:16px"><h1>Frage erfassen</h1><div class="chips"><span class="pill lilac">Tour-ID<br>${esc(state.tour.tourId)}</span><span class="pill lime">Station<br>${esc(station.station || '')}</span><span class="pill mint">Guide<br>${esc(state.tour.guide)}</span></div><label>Kategorie</label><select id="category">${opts(CATEGORIES, 'Prozesse')}</select><label>Priorität</label><div class="chips">${PRIORITIES.map(priority => `<button class="pill" data-priority="${esc(priority)}">${esc(priority)}</button>`).join('')}</div><label>Frage / offener Punkt</label><textarea id="question" rows="5" placeholder="Ihre Frage oder Ihr offener Punkt..."></textarea><label>Zuständig (optional)</label><input id="owner" placeholder="z. B. Technik, IT, Bau, Logistik ..."><button id="save" class="btn primary">▣ Frage speichern</button><p class="small">Wird der aktuellen Führung eindeutig zugeordnet.</p></section>`; let selectedPriority = 'Mittel'; document.querySelectorAll('[data-priority]').forEach(button => { button.classList.toggle('active', button.dataset.priority === selectedPriority); button.onclick = () => { selectedPriority = button.dataset.priority; document.querySelectorAll('[data-priority]').forEach(item => item.classList.toggle('active', item.dataset.priority === selectedPriority)); }; }); $('save').onclick = async () => { const questionText = $('question').value.trim(); if (!questionText) return msg('Bitte Frage eingeben.'); const question = { frageId: 'Q-' + Date.now(), tourId: state.tour.tourId, stationNr: station.order || state.i + 1, station: station.station || '', category: $('category').value, priority: selectedPriority, question: questionText, owner: $('owner').value.trim(), status: 'offen', answer: '', createdAt: new Date().toISOString() }; state.questions.unshift(question); localStorage.tourpilot_questions = JSON.stringify(state.questions); if (API_URL) { try { await api('saveQuestion', question); await loadQuestions(); msg('Frage im Google Sheet gespeichert.'); } catch (error) { msg('Frage lokal gespeichert – Sheet gerade nicht erreichbar.'); } } else msg('Frage lokal gespeichert.'); state.view = 'tour'; render(); }; }
async function questionsView() { if (API_URL && state.tour?.tourId) await loadQuestions(); const currentTourQuestions = state.questions.filter(q => !state.tour || q.tourId === state.tour.tourId); const filteredQuestions = state.filter === 'Alle' ? currentTourQuestions : currentTourQuestions.filter(q => q.status === state.filter); screen.innerHTML = `<section class="grid" style="padding-top:16px"><div class="split"><h1>Offene Fragen</h1><span class="pill">${esc(state.tour?.tourId || 'keine Tour')}</span></div><div class="chips">${['Alle', ...STATUS].map(status => `<button class="pill ${state.filter === status ? 'active' : ''}" data-filter="${esc(status)}">${esc(status)}</button>`).join('')}</div><div class="grid">${filteredQuestions.length ? filteredQuestions.map(qcard).join('') : '<div class="card empty"><h2>Noch keine Fragen erfasst.</h2><p>Fragen können direkt bei der passenden Station gespeichert werden.</p></div>'}</div></section>`; document.querySelectorAll('[data-filter]').forEach(button => { button.onclick = () => { state.filter = button.dataset.filter; render(); }; }); }
function qcard(question) { const color = question.status === 'beantwortet' ? 'lime' : question.status === 'in Abklärung' ? 'mint' : 'lilac'; return `<article class="card ${color}"><div class="qmeta"><span>Station ${esc(question.stationNr)} – ${esc(question.station)}</span><span class="pill">${esc(question.status)}</span></div><div class="qtext">${esc(question.question)}</div><div class="qmeta"><span>Kategorie: ${esc(question.category)}</span><span>${esc(question.priority)}</span></div>${question.owner ? `<p class="small">Zuständig: ${esc(question.owner)}</p>` : ''}</article>`; }
function finishView() { const currentTourQuestions = state.questions.filter(q => !state.tour || q.tourId === state.tour.tourId); const open = currentTourQuestions.filter(q => q.status === 'offen').length; const inProgress = currentTourQuestions.filter(q => q.status === 'in Abklärung').length; const answered = currentTourQuestions.filter(q => q.status === 'beantwortet').length; screen.innerHTML = `<section class="grid" style="padding-top:16px"><h1>Tour abschliessen</h1><article class="card creme"><h2>${esc(state.tour?.tourId || 'Keine Tour aktiv')}</h2><p class="small">${esc(state.tour?.date || '')} · ${esc(state.tour?.startTime || '')} · ${esc(state.tour?.guide || '')}</p></article><div class="stats"><div class="stat"><strong>${open}</strong><small>offen</small></div><div class="stat"><strong>${inProgress}</strong><small>in Abklärung</small></div><div class="stat"><strong>${answered}</strong><small>beantwortet</small></div></div><button id="finish" class="btn petrol">⚑ Tour abschliessen</button><button id="copy" class="btn ghost">Zusammenfassung kopieren</button></section>`; $('finish').onclick = async () => { if (API_URL && state.tour) { try { await api('finishTour', state.tour); msg('Tour im Google Sheet abgeschlossen.'); return; } catch (error) {} } msg('Tour abgeschlossen.'); }; $('copy').onclick = () => { const text = currentTourQuestions.map(q => `Station ${q.stationNr} – ${q.station}\n[${q.status}] ${q.category}: ${q.question}`).join('\n\n'); navigator.clipboard.writeText(text || 'Keine offenen Fragen erfasst.').then(() => msg('Zusammenfassung kopiert.')); }; }
function api(action, params = {}) { return new Promise((resolve, reject) => { const callbackName = 'tp_' + Date.now() + Math.floor(Math.random() * 999); const url = new URL(API_URL); url.searchParams.set('action', action); url.searchParams.set('callback', callbackName); Object.entries(params).forEach(([key, value]) => url.searchParams.set(key, typeof value === 'object' ? JSON.stringify(value) : value)); const script = document.createElement('script'); const timer = setTimeout(() => cleanup(new Error('Timeout')), 12000); window[callbackName] = payload => { if (payload && payload.ok === false) cleanup(new Error(payload.error || 'API Fehler')); else cleanup(null, payload || {}); }; script.onerror = () => cleanup(new Error('API Fehler')); script.src = url.toString(); document.body.appendChild(script); function cleanup(error, payload) { clearTimeout(timer); delete window[callbackName]; script.remove(); error ? reject(error) : resolve(payload); } }); }
function opts(items, selected) { return items.map(item => `<option ${item === selected ? 'selected' : ''}>${esc(item)}</option>`).join(''); }
function list(text) { return String(text || '').split('\n').map(item => item.trim()).filter(Boolean).slice(0, 7); }
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
function icon(station) { const text = ((station.station || '') + ' ' + (station.topic || '')).toLowerCase(); if (text.includes('garderobe') || text.includes('wäsche')) return '▥'; if (text.includes('op')) return '✚'; if (text.includes('notfall')) return '⚑'; if (text.includes('labor')) return '⌬'; if (text.includes('dach')) return '♧'; return '⌖'; }
function msg(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(msg.timer); msg.timer = setTimeout(() => toast.classList.remove('show'), 3000); }
