const API_URL=''; // Apps-Script-Web-App-URL hier eintragen
const GUIDES=['Alexandra','Lea','Damaris','Stefan','Carmen'];
const CATEGORIES=['Bau','Betrieb','Prozesse','IT / Technik','Sicherheit','Ausstattung / Material','Kommunikation','Sonstiges'];
const PRIORITIES=['Niedrig','Mittel','Hoch'];
const STATUS=['offen','in Abklärung','beantwortet'];
const DEMO=[
{order:'Start',floor:'',station:'Start',topic:'Badge beim Hauptempfang Securitas abholen\nBlaue Überzieher-Schuhe richten\nPräsenzkontrolle durchführen',special:'',way:'',nextStation:'Eingang Mitarbeitende'},
{order:1,floor:'0',station:'Eingang Mitarbeitende',topic:'Zutrittsmanagement\nBadgesteuerung\nLiftsteuerung',special:'Bettenlift nur für Patiententransporte',way:'Ambi Treppe C m. Badge → zu Fuss ins UG2 zur Wäscheausgabe',nextStation:'Wäscheausgabe'},
{order:2,floor:'UG2',station:'Wäscheausgabe',topic:'Regelung Berufswäsche',special:'',way:'zu Fuss zu Garderobe',nextStation:'Garderobe'},
{order:3,floor:'UG2',station:'Garderobe',topic:'Nutzung Garderobenschränke\nZuteilung persönliche Schliessfächer',special:'persönliche Schliessfächer nur für MA mit Berufswäsche\nSammlung der dreckigen Berufswäsche vor Lift',way:'Treppe B → zu Fuss ins UG1 zum Foyer',nextStation:'Foyer und Aula'},
{order:4,floor:'UG1',station:'Foyer und Aula',topic:'Rapportraum Ärzte plus grosse Sitzungszimmer',special:'Buchen von Ressourcen\nDurchführung von Weiterbildungen',way:'zu Fuss zu Skillsräumen',nextStation:'Skillsräume'},
{order:5,floor:'UG1',station:'Skillsräume',topic:'PBLS - Kurse und Skills-Training',special:'Buchung über Aus-Fort- und Weiterbildung notwendig',way:'zu Fuss zum Empfang der Radiologie',nextStation:'Radiologie'},
{order:6,floor:'UG1',station:'Radiologie',topic:'Empfang Radiologie für Patienten zu Fuss',special:'Wegführung liegender Patienten erwähnen',way:'zu Fuss zum Empfang der Therapien',nextStation:'Therapien'},
{order:7,floor:'UG1',station:'Therapien',topic:'Besichtigung von einem Behandlungszimmer und einem Therapieraum',special:'Wartebereich Therapien und PP erwähnen\nRundgang Therapiebereich',way:'Haupttreppenhaus → zu Fuss über grosses Treppenhaus in die Eingangshalle',nextStation:'Empfang'},
{order:8,floor:'0',station:'Empfang',topic:'Aufenthaltsraum und Snackautomaten\nAED und Notfallsituationen\nPatientenempfang',special:'AED und REA sind mit Schildern im ganzen Haus gekennzeichnet',way:'zu Fuss zum Eingang Notfall',nextStation:'Notfall'},
{order:9,floor:'0',station:'Notfall',topic:'Ambulanzvorfahrt\nZufahrt Notfall mit Parkplatz',special:'Eingang nur für Patienten und Angehörige',way:'zu Fuss zum Schockraum',nextStation:'Notfall Schockraum'},
{order:10,floor:'0',station:'Notfall Schockraum',topic:'Schockraum\nStationszentrale / Wartebereich',special:'',way:'zu Fuss zum Empfang 1 Ambi',nextStation:'Ambi Empfang 1'},
{order:11,floor:'0',station:'Ambi Empfang 1',topic:'Empfang 1 mit den zugehörigen Clustern',special:'',way:'zu Fuss zum Empfang 2 Ambi',nextStation:'Ambi Empfang 2'},
{order:12,floor:'0',station:'Ambi Empfang 2',topic:'Empfang 2 mit den zugehörigen Clustern',special:'Patientenprozess im Bereich Ambulatorium',way:'zu Fuss zum Marktplatz Ambi',nextStation:'Ambi Marktplatz'},
{order:13,floor:'0',station:'Ambi Marktplatz',topic:'Marktplatz',special:'Pausen und Mitarbeiterverpflegung',way:'Nur Lift C möglich → mit dem Lift in den 8. Stock',nextStation:'Bürowelt'},
{order:14,floor:'8',station:'Bürowelt',topic:'Aufteilung Fachbereiche Stock 8 und 9 inkl. Signaletik',special:'Besucher Anmeldung Hauptempfang und abholen\nBettenlifte nur für Patienten- und Gütertransporte',way:'Rundgang durch Cluster Pflege und Pädiatrie zu Lounge',nextStation:'Bürowelt Lounge'},
{order:15,floor:'8',station:'Bürowelt Lounge',topic:'Nutzung Open Space Büro\nBesprechungszimmer\nDruckerräume\nDiktierboxen\nLounge',special:'Garderobe Bürowelt\nLiftsteuerung mit Badge\nInformation Buchung von Sitzungszimmer',way:'Treppe B → zu Fuss mit Treppe B auf Station 7 Gartenzimmer',nextStation:'Station 7 Gartenzimmer'},
{order:16,floor:'7',station:'Station 7 Gartenzimmer',topic:'Gartenzimmer',special:'interdisziplinäre Säugling- und Kleinkindstation',way:'Rundgang durch Station im Uhrzeigersinn',nextStation:'Station 7'},
{order:17,floor:'7',station:'Station 7',topic:'Stationsrundgang mit Empfang\nStationszentrale\nSpielen\nFamilienaufenthalt\nPatientenzimmer\nApotheke\nLager',special:'Apotheke badgegesteuert\nSignaletik Korridor\nKanbansystem',way:'Treppe A → zu Fuss mit Treppe A auf Station 6',nextStation:'Station 6'},
{order:18,floor:'6',station:'Station 6',topic:'Besichtigung Wohnen und Essen Patienten\nTime Out - Zimmer',special:'Patientenzuteilung erwähnen\nKJM > 3 Jahre und PP\nKJC > 3 Jahre = Station 5',way:'Treppe A → zu Fuss mit Treppe 07 auf Station 4',nextStation:'Station 4'},
{order:19,floor:'4',station:'Station 4',topic:'Gartenzimmer',special:'Onkologie ambulant und stationär',way:'Treppe B → zu Fuss mit Treppe B in 3. Stock',nextStation:'Spitalpädagogik'},
{order:20,floor:'3',station:'Spitalpädagogik',topic:'Besichtigung von Schulzimmer und Werkraum',special:'',way:'zu Fuss zu Ruhe- und Pikettzimmern',nextStation:'Pikett- und Ruhezimmer'},
{order:21,floor:'3',station:'Pikett- und Ruhezimmer',topic:'Übernachtung und Abpumpmöglichkeit für Mitarbeitende',special:'Regelung Pikettzimmer\nBürowelt Chirurgie / Orthopädie',way:'zu Fuss zum Labor',nextStation:'Labor'},
{order:22,floor:'3',station:'Labor',topic:'Glocke und Schleuse für Laborproben\nBlutentnahmeraum',special:'Anmeldung mit Glocke und Wartebereich\nSchleuse für Laborproben',way:'zu Fuss zur Türe Dachgarten',nextStation:'Dachgarten'},
{order:23,floor:'3',station:'Dachgarten',topic:'Spielplatz',special:'Übergang zum Restaurant Roof Garden HOCH\nDefinierte Öffnungszeiten für Pat. und Angehörige',way:'Haupttreppenhaus → zu Fuss über grosses Treppenhaus in 2. Geschoss',nextStation:'OP/Anästhesie'},
{order:24,floor:'2',station:'OP/Anästhesie',topic:'Multifunktionsraum 1',special:'Kleine ambulante Eingriffe',way:'Rundgang durch Bereich OP/Anästhesie',nextStation:'OP 1'},
{order:25,floor:'2',station:'OP 1',topic:'Ein- und Ausleitung OP 1\nOP 1',special:'1 Person und Pflegende dürfen bei der Anästhesieeinleitung dabei sein',way:'zu Fuss',nextStation:'Aufwachraum'},
{order:26,floor:'2',station:'Aufwachraum',topic:'Aufwachraum',special:'Eltern mit Pflege können Kinder in Aufwachraum begleiten',way:'zu Fuss zu Zimmer 231 und 229',nextStation:'Tagesklinik'},
{order:27,floor:'2',station:'Tagesklinik',topic:'Patientenzimmer',special:'2 4-er Zimmer\n4 2-er Zimmer',way:'Haupttreppenhaus → zu Fuss über grosses Treppenhaus auf Station 1',nextStation:'Station 1'},
{order:28,floor:'1',station:'Station 1',topic:'Stationsrundgang: Zimmer NEO 1\nZimmer NEO 2\nZimmer IPS und IMC',special:'Couplet Care\nNEO 1 und NEO 2\nIPS Intensivstation und IMC',way:'zu Fuss',nextStation:'Passerelle'},
{order:29,floor:'1',station:'Passerelle',topic:'Passerelle zum Gebärsaal und Frauenklinik',special:'Erstversorgung',way:'zu Fuss zu Milchküche/Stillberatung',nextStation:'Milchküche / Stillberatung'},
{order:30,floor:'1',station:'Milchküche / Stillberatung',topic:'Abgabe Muttermilch, Abpumpmöglichkeit Mütter',special:'',way:'zu Fuss zu Feuerwehrlift',nextStation:'Feuerwehrlift'},
{order:31,floor:'1',station:'Feuerwehrlift',topic:'Prioritärer Zugang für REA-Equipe\nZugang zu Helilandeplatz\nTransport von Patienten auf und von IPS\nReanimation im OKS',special:'keine Besichtigung aus Sicherheitsgründen\nAbgabe REA-Karten für Mitarbeitende mit Patientenkontakt',way:'Haupttreppenhaus → zu Fuss über Treppe ins EG zum Eingang Mitarbeitende',nextStation:'Haupteingang'},
{order:32,floor:'0',station:'Haupteingang',topic:'Abschluss Führung',special:'',way:'',nextStation:'Tour abschliessen'}
];
const state={view:'start',stations:DEMO,i:0,questions:JSON.parse(localStorage.tourpilot_questions||'[]'),tour:JSON.parse(localStorage.tourpilot_tour||'null'),filter:'Alle'};
const $=id=>document.getElementById(id), screen=$('screen'), toast=$('toast');
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});
$('menu').onclick=()=>msg(API_URL?'Live-Verbindung vorbereitet.':'Demo-Modus: Apps-Script-URL in app.js eintragen.');
loadStations().then(render);
async function loadStations(){if(!API_URL)return;try{const r=await api('getStations');if(r.stations?.length)state.stations=r.stations}catch(e){msg('Google Sheet nicht erreichbar – Demo-Daten geladen.')}}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view||(state.view==='questionForm'&&b.dataset.view==='questions')));if(state.view==='tour')return tourView();if(state.view==='questionForm')return questionForm();if(state.view==='questions')return questionsView();if(state.view==='finish')return finishView();return startView()}
function startView(){let d=new Date(),date=state.tour?.date||d.toISOString().slice(0,10),time=state.tour?.startTime||d.toTimeString().slice(0,5);screen.innerHTML=`<section class="hero"><div><h1>Neubau TourPilot</h1><p>Mobiler Guide für Mitarbeitenden-Führungen</p></div></section><section class="grid"><h1>Tour starten</h1>${row('◷','Datum',`<input id="date" type="date" value="${esc(date)}">`)}${row('♟','Guide',`<select id="guide">${opts(GUIDES,state.tour?.guide||'Carmen')}</select>`)}${row('⌁','Tour-ID / Führung',`<input id="tourId" value="${esc(state.tour?.tourId||'Führung '+date.replaceAll('-',''))}">`)}${row('☷','Gruppe',`<input id="group" placeholder="z. B. Team Pflege" value="${esc(state.tour?.group||'')}">`)}${row('◴','Startzeit',`<input id="startTime" type="time" value="${esc(time)}">`)}<button id="start" class="btn primary">▶ Tour starten</button><div class="card lime"><strong>Standardroute – ${state.stations.length} Stationen</strong><p class="small">Fragen werden mit Tour-ID, Guide und Station gespeichert.</p></div></section>`;$('start').onclick=startTour}
function row(icon,label,field){return `<div class="row"><span>${icon}</span><div><label>${label}</label>${field}</div></div>`}
async function startTour(){state.tour={date:$('date').value,guide:$('guide').value,tourId:$('tourId').value.trim(),group:$('group').value.trim(),startTime:$('startTime').value,status:'offen'};if(!state.tour.tourId)return msg('Bitte Tour-ID eingeben.');localStorage.tourpilot_tour=JSON.stringify(state.tour);if(API_URL)try{await api('saveTour',state.tour)}catch(e){msg('Tour lokal gestartet.')}state.i=0;state.view='tour';render()}
function tourView(){if(!state.tour){state.view='start';return render()}let s=state.stations[state.i],n=state.i+1,total=state.stations.length,p=Math.round(n/total*100),points=[...list(s.topic),...list(s.special).slice(0,3)];screen.innerHTML=`<section class="grid" style="padding-top:14px"><div class="card"><div class="split"><strong>Station ${n} von ${total}</strong><strong>${p}%</strong></div><div class="progress"><div class="bar" style="width:${p}%"></div></div></div><article class="card"><div class="stationHead"><div class="stationIcon">${icon(s)}</div><div><div class="kicker">${esc(state.tour.tourId)} · ${esc(state.tour.guide)}</div><h1>${esc(s.station)}</h1>${s.floor?`<p>Geschoss: <span class="floor">${esc(s.floor)}</span></p>`:''}</div></div>${points.length?`<ul class="bullets">${points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="small">Keine Detailpunkte hinterlegt.</p>'}</article><article class="card lilac next"><div class="round">👣</div><div><div class="kicker">Nächste Station</div><strong>${esc(s.nextStation)}</strong></div><span>›</span></article><article class="card mint next"><div class="round">⇄</div><div><div class="kicker">Weg</div><strong>${esc(s.way||s.access||'Keine Wegführung hinterlegt')}</strong></div></article><div class="twocol"><button id="ask" class="btn ghost">✎ Frage erfassen</button><button id="next" class="btn primary">${n>=total?'Abschluss':'Weiter'} ›</button></div><button id="prev" class="btn ghost" ${state.i===0?'disabled':''}>‹ Zurück</button></section>`;$('ask').onclick=()=>{state.view='questionForm';render()};$('next').onclick=()=>{if(state.i+1>=total)state.view='finish';else state.i++;render()};$('prev').onclick=()=>{state.i=Math.max(0,state.i-1);render()}}
function questionForm(){let s=state.stations[state.i];screen.innerHTML=`<section class="grid" style="padding-top:16px"><h1>Frage erfassen</h1><div class="chips"><span class="pill open">Tour-ID: ${esc(state.tour?.tourId||'-')}</span><span class="pill">Station: ${esc(s.station)}</span><span class="pill">Guide: ${esc(state.tour?.guide||'-')}</span></div><label class="grid">Kategorie<select id="cat">${opts(CATEGORIES,'Prozesse')}</select></label><label class="grid">Priorität<select id="prio">${opts(PRIORITIES,'Mittel')}</select></label><label class="grid">Frage / offener Punkt<textarea id="q" placeholder="Ihre Frage oder Ihr offener Punkt..."></textarea></label><label class="grid">Zuständig optional<input id="owner" placeholder="z. B. Technik, IT, Bau, Logistik ..."></label><button id="save" class="btn green">▣ Frage speichern</button><p class="small">Wird der aktuellen Führung eindeutig zugeordnet.</p></section>`;$('save').onclick=saveQuestion}
async function saveQuestion(){let s=state.stations[state.i],text=$('q').value.trim();if(!text)return msg('Bitte zuerst eine Frage eingeben.');let q={frageId:'Q-'+Date.now(),tourId:state.tour.tourId,stationNr:state.i+1,station:s.station,category:$('cat').value,priority:$('prio').value,question:text,owner:$('owner').value.trim(),status:'offen',answer:'',createdAt:new Date().toISOString()};if(API_URL)try{await api('saveQuestion',q)}catch(e){msg('Frage lokal gespeichert.')}state.questions=[q,...state.questions];localStorage.tourpilot_questions=JSON.stringify(state.questions);state.view='questions';render();msg('Frage gespeichert.')}
function questionsView(){let qs=state.questions.filter(q=>!state.tour||q.tourId===state.tour.tourId),f=state.filter==='Alle'?qs:qs.filter(q=>q.status===state.filter);screen.innerHTML=`<section class="grid" style="padding-top:16px"><div class="split"><h1>Offene Fragen</h1><span class="pill">${esc(state.tour?.tourId||'keine Tour')}</span></div><div class="chips">${['Alle',...STATUS].map(x=>`<button class="pill ${state.filter===x?'active':''}" data-filter="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="grid">${f.length?f.map(qcard).join(''):'<div class="card empty"><h2>Noch keine Fragen erfasst.</h2><p>Fragen können direkt bei der passenden Station gespeichert werden.</p></div>'}</div></section>`;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()})}
function qcard(q){let c=q.status==='beantwortet'?'lime':q.status==='in Abklärung'?'mint':'lilac';return `<article class="card ${c}"><div class="qmeta"><span>Station ${esc(q.stationNr)} – ${esc(q.station)}</span><span class="pill">${esc(q.status)}</span></div><div class="qtext">${esc(q.question)}</div><div class="qmeta"><span>Kategorie: ${esc(q.category)}</span><span>${esc(q.priority)}</span></div>${q.owner?`<p class="small">Zuständig: ${esc(q.owner)}</p>`:''}</article>`}
function finishView(){let qs=state.questions.filter(q=>!state.tour||q.tourId===state.tour.tourId),o=qs.filter(q=>q.status==='offen').length,a=qs.filter(q=>q.status==='in Abklärung').length,b=qs.filter(q=>q.status==='beantwortet').length;screen.innerHTML=`<section class="grid" style="padding-top:16px"><h1>Tour abschliessen</h1><article class="card creme"><h2>${esc(state.tour?.tourId||'Keine Tour aktiv')}</h2><p class="small">${esc(state.tour?.date||'')} · ${esc(state.tour?.startTime||'')} · ${esc(state.tour?.guide||'')}</p></article><div class="stats"><div class="stat"><strong>${o}</strong><small>offen</small></div><div class="stat"><strong>${a}</strong><small>in Abklärung</small></div><div class="stat"><strong>${b}</strong><small>beantwortet</small></div></div><button id="finish" class="btn petrol">⚑ Tour abschliessen</button><button id="copy" class="btn ghost">Zusammenfassung kopieren</button></section>`;$('finish').onclick=async()=>{if(API_URL&&state.tour)try{await api('finishTour',state.tour)}catch(e){}msg('Tour abgeschlossen.')};$('copy').onclick=()=>navigator.clipboard.writeText(qs.map(q=>`Station ${q.stationNr} – ${q.station}\n[${q.status}] ${q.category}: ${q.question}`).join('\n\n')).then(()=>msg('Zusammenfassung kopiert.'))}
function api(action,params={}){return new Promise((res,rej)=>{let cb='tp_'+Date.now()+Math.floor(Math.random()*999),u=new URL(API_URL);u.searchParams.set('action',action);u.searchParams.set('callback',cb);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,typeof v==='object'?JSON.stringify(v):v));let s=document.createElement('script'),t=setTimeout(()=>clean(new Error('Timeout')),12000);window[cb]=p=>p?.ok===false?clean(new Error(p.error)):clean(null,p);s.onerror=()=>clean(new Error('API Fehler'));s.src=u;document.body.appendChild(s);function clean(e,p){clearTimeout(t);delete window[cb];s.remove();e?rej(e):res(p)}})}
function opts(a,sel){return a.map(x=>`<option ${x===sel?'selected':''}>${esc(x)}</option>`).join('')}function list(t){return String(t||'').split('\n').map(x=>x.trim()).filter(Boolean).slice(0,7)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function icon(s){let t=(s.station+' '+s.topic).toLowerCase();if(t.includes('garderobe')||t.includes('wäsche'))return'▥';if(t.includes('op'))return'✚';if(t.includes('notfall'))return'⚑';if(t.includes('labor'))return'⌬';if(t.includes('dach'))return'♧';return'⌖'}function msg(m){toast.textContent=m;toast.classList.add('show');clearTimeout(msg.t);msg.t=setTimeout(()=>toast.classList.remove('show'),3000)}
